---
# # tasks file for seedlink
# - name: gather os specific variables
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "vars/{{ ansible_distribution }}-\
#       {{ ansible_distribution_major_version }}.yml"
#     - "vars/{{ ansible_distribution }}.yml"
#     - "vars/{{ ansible_os_family }}.yml"
- name: install dependencies
  apt:
    pkg:
      - git
      - g++
      - cmake
      - libboost-dev
      - libxml2-dev
      - flex
      - libfl-dev
      - libssl-dev
      - libcrypto++-dev
      # - build-essential
      - python3-dev
      - libboost-test-dev
      - libboost-system-dev
      - libboost-program-options-dev

- name: Clone seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seiscomp.git
    dest: /src/seiscomp

- name: Clone seedlink plugin for seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seedlink.git
    dest: /src/seiscomp/src/base/seedlink

- name: Create build directory
  ansible.builtin.shell: mkdir build
  args:
    chdir: /src/seiscomp/
    creates: /src/seiscomp/build

- name: cmake seiscomp
  ansible.builtin.shell:
  args:
    chdir: /src/seiscomp/build
    creates: Makefile
    cmd: cmake /src/seiscomp -DCMAKE_INSTALL_PREFIX=/opt/seiscomp

- name: Compile seiscomp
  community.general.make:
    chdir: /src/seiscomp/build

- name: Install seiscomp
  community.general.make:
    chdir: /src/seiscomp/build
    target: install
  become: true

- name: Copy systemd service file to server
  copy:
    src: seedlink.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start seedlink
