---
# # tasks file for seedlink
# - name: gather os specific variables
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "vars/{{ ansible_distribution }}-\
#       {{ ansible_distribution_major_version }}.yml"
#     - "vars/{{ ansible_distribution }}.yml"
#     - "vars/{{ ansible_os_family }}.yml"
- name: Add the user 'sysop' with a bash shell, appending the group 'admin', 'adm','audio' and 'sysop' to the user's groups
  ansible.builtin.user:
    name: "{{ ansible_seedlink_user }}"
    shell: /bin/bash
    groups: admin,adm,audio,{{ ansible_seedlink_user }}
    append: yes

- name: install dependencies
  apt:
    pkg:
      - git
      - g++
      - cmake
      - libboost-dev
      - libxml2-dev
      - flex
      - libfl-dev
      - libssl-dev
      - libcrypto++-dev
      # - build-essential
      - python3-dev
      - libboost-test-dev
      - libboost-system-dev
      - libboost-program-options-dev

- name: Clone seiscomp into /src/seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seiscomp.git
    dest: /src/seiscomp

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /src/seiscomp
    owner: "{{ ansible_seedlink_user }}"
    group: "{{ ansible_seedlink_user }}"
    recurse: yes

- name: Clone seedlink plugin for seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seedlink.git
    dest: /src/seiscomp/src/base/seedlink
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Create a target directory if it does not exist
  ansible.builtin.file:
    path: /opt/seiscomp
    state: directory
    mode: '0755'
    owner: "{{ ansible_seedlink_user }}"
    group: "{{ ansible_seedlink_user }}"

- name: Create build directory
  ansible.builtin.shell: mkdir build
  args:
    chdir: /src/seiscomp/
    creates: /src/seiscomp/build
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: cmake seiscomp
  ansible.builtin.shell:
  args:
    chdir: /src/seiscomp/build
    creates: Makefile
    cmd: cmake /src/seiscomp -DCMAKE_INSTALL_PREFIX=/opt/seiscomp
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Compile seiscomp
  community.general.make:
    chdir: /src/seiscomp/build
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Install seiscomp
  community.general.make:
    chdir: /src/seiscomp/build
    target: install
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Copy systemd service file to server
  copy:
    src: seedlink.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start seedlink
