---

- name: Add the user 'sysop' with a bash shell, appending the group 'admin', 'adm','audio' and 'sysop' to the user's groups
  ansible.builtin.user:
    name: "{{ ansible_seedlink_user }}"
    shell: /bin/bash
    groups: admin,adm,audio,{{ ansible_seedlink_user }}
    append: yes

- name: install dependencies
  apt:
    pkg:
      - git
      - g++
      - cmake
      - libboost-dev
      - libxml2-dev
      - flex
      - libfl-dev
      - libssl-dev
      - libcrypto++-dev
      - python3-dev
      - maria-db
      - libboost-test-dev
      - libboost-system-dev
      - libboost-program-options-dev

# These packages need further investigatin which ones are strict requirements of the
# seedlink module:
# running install based installed the following:
# libblas3 libboost-filesystem1.71.0 libboost-iostreams1.71.0
#  libboost-regex1.71.0 libboost-thread1.71.0 libgfortran5 liblapack3 libmariadb3
#  libmysqlclient21 libncurses5 libpq5 libtinfo5 mariadb-common mysql-common
#  python3-numpy mariadb-server

- name: Clone seiscomp into /src/seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seiscomp.git
    dest: /src/seiscomp

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /src/seiscomp
    owner: "{{ ansible_seedlink_user }}"
    group: "{{ ansible_seedlink_user }}"
    recurse: yes

- name: Clone seedlink plugin for seiscomp
  ansible.builtin.git:
    repo: https://github.com/SeisComP/seedlink.git
    dest: /src/seiscomp/src/base/seedlink
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Create a target directory if it does not exist
  ansible.builtin.file:
    path: /opt/seiscomp
    state: directory
    mode: '0755'
    owner: "{{ ansible_seedlink_user }}"
    group: "{{ ansible_seedlink_user }}"

- name: Create build directory
  ansible.builtin.shell: mkdir build
  args:
    chdir: /src/seiscomp/
    creates: /src/seiscomp/build
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: cmake seiscomp
  ansible.builtin.shell:
  args:
    chdir: /src/seiscomp/build
    creates: Makefile
    cmd: cmake /src/seiscomp -DCMAKE_INSTALL_PREFIX=/opt/seiscomp
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Compile seiscomp
  community.general.make:
    chdir: /src/seiscomp/build
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Install seiscomp
  community.general.make:
    chdir: /src/seiscomp/build
    target: install
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: Copy seedlink configuration
  copy:
    src: seedlink.cfg
    dest: /opt/seiscomp/etc
    owner: "{{ ansible_seedlink_user }}"
    group: "{{ ansible_seedlink_user }}"

# This exits straight away and it's unclear why:
#- name: setup seiscomp
#  ansible.builtin.shell: ./seiscomp setup
#  args:
#    chdir: /opt/seiscomp/bin
#  become: yes
#  become_user: "{{ ansible_seedlink_user }}"

# To update the configuration when new stations have been added or modified,
# seiscomp update-config needs to be run.
# Place inventory into /etc/inventory, then run
#  seiscomp update-config inventory
- name: update seiscomp config
  ansible.builtin.shell: ./seiscomp update-config seedlink
  args:
    chdir: /opt/seiscomp/bin
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

- name: update seiscomp config
  ansible.builtin.shell: ./seiscomp start seedlink
  args:
    chdir: /opt/seiscomp/bin
  become: yes
  become_user: "{{ ansible_seedlink_user }}"

# ./bin/seiscomp setup
# ./bin/seiscomp update-conf
